// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSEeiRUEyqEnz2N4siP0N-XznLlaI_uqI',
    appId: '1:249044615071:web:4bf426df4fecde631bc7aa',
    messagingSenderId: '249044615071',
    projectId: 'workherway-18d98',
    authDomain: 'workherway-18d98.firebaseapp.com',
    storageBucket: 'workherway-18d98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpch0GYJwo-Z19umoBwaorgw1LGOgOQik',
    appId: '1:249044615071:android:050ac8705eb026c41bc7aa',
    messagingSenderId: '249044615071',
    projectId: 'workherway-18d98',
    storageBucket: 'workherway-18d98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxl6JLdr3HqiL8JWW4ejydrny1L5uek3Y',
    appId: '1:249044615071:ios:149aeaea104b9e1e1bc7aa',
    messagingSenderId: '249044615071',
    projectId: 'workherway-18d98',
    storageBucket: 'workherway-18d98.appspot.com',
    iosBundleId: 'com.example.laptopfyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxl6JLdr3HqiL8JWW4ejydrny1L5uek3Y',
    appId: '1:249044615071:ios:f81369c8486c141d1bc7aa',
    messagingSenderId: '249044615071',
    projectId: 'workherway-18d98',
    storageBucket: 'workherway-18d98.appspot.com',
    iosBundleId: 'com.example.laptopfyp.RunnerTests',
  );
}
